chain_config: ./genesis.json
secrets_config: ""
data_dir: "./nodes/test-chain-1"
block_gas_target: "0x3938700"
grpc_addr: "0.0.0.0:10005"
jsonrpc_addr: "0.0.0.0:10007"
telemetry:
  prometheus_addr: ""
network:
  no_discover: false
  libp2p_addr: 0.0.0.0:10006
  nat_addr: ""
  dns_addr: ""
  max_peers: -1
  max_outbound_peers: -1
  max_inbound_peers: -1
seal: true
tx_pool:
  price_limit: 0
  max_slots: 4096
log_level: INFO
restore_file: ""
block_time_s: 2
headers:
  access_control_allow_origins:
    - '*'
log_to: ""